version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      - .:/app
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
